apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: networkio
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: networkstatic/iperf3
        name: iperf3 
        args: ['-c', 'server', '--parallel', '40', '-i', '1', '-t', 'inf']
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - server
            topologyKey: kubernetes.io/hostname
