apiVersion: v1
kind: Namespace
metadata:
  name: networkio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: networkio
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: networkstatic/iperf3
        name: iperf3 
        args: ['-s']
        ports:
        - containerPort: 5201 

---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: networkio
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5201

